In [10]:
import json
import requests

# Load secrets from credentials.json
url = 'https://api.foursquare.com/v2/venues/explore'
with open('.secrets/credentials.json') as f:
    params = json.load(f)

In [14]:
params['v'] = '20190717'
params['ll'] = '47.608,-122.336',
params['query'] = 'yoga',
params['intent'] = 'browse',
params['radius'] = 100000,
params['limit'] = 100

In [15]:
response = requests.get(url=url, params=params)
data = json.loads(response.text)

In [24]:
groups = data['response']['groups']

In [26]:
items = groups[0]['items']

In [27]:
len(items)

100

In [16]:
data.keys()

dict_keys(['meta', 'response'])

In [17]:
data['response'].keys()

dict_keys(['suggestedFilters', 'headerLocation', 'headerFullLocation', 'headerLocationGranularity', 'query', 'totalResults', 'suggestedBounds', 'groups'])

In [18]:
data['meta']

{'code': 200, 'requestId': '5d2fa1fed69ed0002cbe3592'}

In [19]:
results = data['response']['groups'][0]['items']

In [ ]:
item = items[0]

In [ ]:
[get_name(item) for item in items]

In [38]:
# or make function
def get_name(item):
    return item['venue']['name']

def get_address(item):
    return item['venue']['location'].get('address')

In [61]:
item_data = ({'name': get_name(item),
              'address': get_address(item),}
               for item in items)

item_data #

In [54]:
import pandas as pd
pd.DataFrame({'name': get_name(item),
              'address': get_address(item),}
               for item in items).head()

                        address               name
0                  1900 4th Ave     Urban Yoga Spa
1         900 Lenora St Ste 128   Be Luminous Yoga
2         2131 Queen Anne Ave N         Haute Yoga
3                 1540 15th Ave  Seattle Yoga Arts
4  1455 NW Leary Way, Suite 100     CorePower Yoga

In [63]:
venues_df = [{'name': get_name(item),
              'address': get_address(item),}
               for item in items]

In [20]:
venues = []
venue_names = []
for result in results:
    venues.append(result['venue'])
    venue_names.append(result['venue']['name'])

In [32]:
item['venue']['name']

'Urban Yoga Spa'

In [42]:
# [item['venue']['name'] for item in items]

In [64]:
len(venues)

100

In [46]:
venue_names[:5]

['Urban Yoga Spa',
 'Be Luminous Yoga',
 'Haute Yoga',
 'Seattle Yoga Arts',
 'CorePower Yoga']

In [65]:
import pymongo
mc = pymongo.MongoClient()
db = mc['foursquare']
coll = db['pilates']

In [66]:
venues = list(coll.find())

In [67]:
found_venues = list(coll.find())

In [68]:
coll.insert_many(venues)

BulkWriteError: batch op errors occurred

In [69]:
found_venues = list(coll.find())
pd.DataFrame(found_venues)

,_id,categories,id,location,name,photos,venuePage
0,5d2fa892df98ea8a5fe358d6,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4a823b1cf964a520f4f81fe3,"{'address': '1900 4th Ave', 'crossStreet': 'at...",Urban Yoga Spa,"{'count': 0, 'groups': []}",NaN
1,5d2fa892df98ea8a5fe358d7,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b08b44ef964a520161123e3,"{'address': '900 Lenora St Ste 128', 'crossStr...",Be Luminous Yoga,"{'count': 0, 'groups': []}",NaN
2,5d2fa892df98ea8a5fe358d8,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4a8e262df964a5201d1220e3,"{'address': '2131 Queen Anne Ave N', 'crossStr...",Haute Yoga,"{'count': 0, 'groups': []}",NaN
3,5d2fa892df98ea8a5fe358d9,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4be7229a334fb7131ae8a0bc,"{'address': '1540 15th Ave', 'crossStreet': 'b...",Seattle Yoga Arts,"{'count': 0, 'groups': []}",NaN
4,5d2fa892df98ea8a5fe358da,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",504b8b51e4b0838e3065d860,"{'address': '1455 NW Leary Way, Suite 100', 'c...",CorePower Yoga,"{'count': 0, 'groups': []}",NaN
5,5d2fa892df98ea8a5fe358db,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",51b5d221498eead65cd90978,"{'address': '501 Broadway E, Suite 1', 'lat': ...",CorePower Yoga,"{'count': 0, 'groups': []}",NaN
6,5d2fa892df98ea8a5fe358dc,"[{'id': '503289d391d4c4b30a586d6a', 'name': 'C...",4d893ccf76e1236a5e480143,"{'address': '900 Poplar Pl S', 'lat': 47.59350...",Seattle Bouldering Project,"{'count': 0, 'groups': []}",NaN
7,5d2fa892df98ea8a5fe358dd,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",49e4f187f964a52075631fe3,"{'address': '500 E Pike St', 'crossStreet': 'a...",8 Limbs Yoga,"{'count': 0, 'groups': []}",NaN
8,5d2fa892df98ea8a5fe358de,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4fb449d4e4b0186ba35fff7c,"{'address': '345 15th Ave E', 'crossStreet': '...",The Grinning Yogi,"{'count': 0, 'groups': []}",NaN
9,5d2fa892df98ea8a5fe358df,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4c3503d166e40f47278aca8b,"{'lat': 47.793150509394636, 'lng': -122.217059...",Fusion Hot Yoga,"{'count': 0, 'groups': []}",NaN
10,5d2fa892df98ea8a5fe358e0,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4c41e93ace54e21effc80b1a,"{'address': '9750 NE 119th Way', 'lat': 47.707...",Bala Yoga,"{'count': 0, 'groups': []}",NaN
11,5d2fa892df98ea8a5fe358e1,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b7ad585f964a520a53f2fe3,"{'address': '8 Boston St', 'lat': 47.638421950...",Yogalife Queen Anne,"{'count': 0, 'groups': []}",NaN
12,5d2fa892df98ea8a5fe358e2,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b2c4b52f964a52066c524e3,"{'address': '10245 Main St', 'crossStreet': 'a...",Shakti Vinyasa Yoga,"{'count': 0, 'groups': []}",NaN
13,5d2fa892df98ea8a5fe358e3,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4d5ee289d979ba7a5a64bdc7,"{'address': '5903 196th St SW', 'lat': 47.8216...",Bindi Yoga,"{'count': 0, 'groups': []}",NaN
14,5d2fa892df98ea8a5fe358e4,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",516a1e08e4b026a6fca409f8,"{'address': '6521 Roosevelt Way NE', 'lat': 47...",Shefayoga,"{'count': 0, 'groups': []}",NaN
15,5d2fa892df98ea8a5fe358e5,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",53b6f759498e1170f313ca16,"{'address': '7110 Woodlawn Ave NE', 'lat': 47....",Modo Yoga,"{'count': 0, 'groups': []}",NaN
16,5d2fa892df98ea8a5fe358e6,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4f35f9e6e4b0d9574b75e5ca,"{'address': '1223 E Cherry St', 'crossStreet':...",Live Love Flow,"{'count': 0, 'groups': []}",NaN
17,5d2fa892df98ea8a5fe358e7,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4a8e2520f964a5201b1220e3,"{'address': '2238 NW Market St', 'crossStreet'...",Shakti Vinyasa Yoga,"{'count': 0, 'groups': []}",NaN
18,5d2fa892df98ea8a5fe358e8,"[{'id': '4bf58dd8d48988d1ed941735', 'name': 'S...",4f358e3ae4b0c48479c4631e,"{'address': '4455 148th Ave NE', 'lat': 47.651...",ProSports Club Spa,"{'count': 0, 'groups': []}",NaN
19,5d2fa892df98ea8a5fe358e9,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",52f2984e11d2921a7bfedf74,"{'address': '10307 NE 10th St', 'crossStreet':...",CorePower Yoga,"{'count': 0, 'groups': []}",NaN
20,5d2fa892df98ea8a5fe358ea,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b3f85adf964a52058a825e3,"{'address': '7803 SE 27th St #174', 'lat': 47....",Yogabliss,"{'count': 0, 'groups': []}",NaN
21,5d2fa892df98ea8a5fe358eb,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",49e39ed3f964a520a1621fe3,"{'address': '1417 10th Ave', 'lat': 47.6136768...",Sweat Box Yoga,"{'count': 0, 'groups': []}",{'id': '88453892'}
22,5d2fa892df98ea8a5fe358ec,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4eada0f430f855f5b364b7c0,"{'address': '13112 NE 20th St', 'lat': 47.6287...",Get Zen Hot Yoga,"{'count': 0, 'groups': []}",NaN
23,5d2fa892df98ea8a5fe358ed,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b945d59f964a5206f7634e3,"{'address': '222 Williams Ave S', 'lat': 47.48...",Bikram Yoga,"{'count': 0, 'groups': []}",NaN
24,5d2fa892df98ea8a5fe358ee,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4aca3977f964a520f1c020e3,"{'address': '11200 SE 6th St', 'lat': 47.60576...",Bellevue Club,"{'count': 0, 'groups': []}",{'id': '47150774'}
25,5d2fa892df98ea8a5fe358ef,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",552dd2dc498e0b5e98028a5c,"{'address': '4535 12th Ave NE, Ste A', 'lat': ...",CorePower Yoga,"{'count': 0, 'groups': []}",NaN
26,5d2fa892df98ea8a5fe358f0,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",521945ed11d244d69e56f626,"{'address': '10004 Aurora Avenue North, Suite ...",CorePower Yoga,"{'count': 0, 'groups': []}",NaN
27,5d2fa892df98ea8a5fe358f1,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",5810066c38fa3355dc0952f1,"{'address': '606 Broadway E', 'lat': 47.624561...",TRIBE Fitness,"{'count': 0, 'groups': []}",{'id': '494657837'}
28,5d2fa892df98ea8a5fe358f2,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4fceab6fe4b08ffd9b7acb72,"{'address': '15600 Northeast 8th Street', 'lat...",Crunch - Bellevue,"{'count': 0, 'groups': []}",{'id': '526734516'}
29,5d2fa892df98ea8a5fe358f3,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b15c1f6f964a520d6b323e3,"{'address': '1415 12th Ave', 'crossStreet': 'b...",Foundation CrossFit,"{'count': 0, 'groups': []}",{'id': '61645818'}
...,...,...,...,...,...,...,...
70,5d2fa892df98ea8a5fe3591c,"[{'id': '4bf58dd8d48988d1ed941735', 'name': 'S...",4bad25bcf964a520ac323be3,"{'address': '1635 8th Ave', 'lat': 47.61374382...",Elaia Spa,"{'count': 0, 'groups': []}",{'id': '33173989'}
71,5d2fa892df98ea8a5fe3591d,"[{'id': '4bf58dd8d48988d176941735', 'name': 'G...",4baeff98f964a5207ce63be3,"{'address': '12138 Mukilteo Speedway', 'lat': ...",Gold's Gym,"{'count': 0, 'groups': []}",{'id': '89440631'}
72,5d2fa892df98ea8a5fe3591e,"[{'id': '4bf58dd8d48988d134941735', 'name': 'D...",4bae208af964a5207a873be3,"{'address': '1621 12th Ave', 'crossStreet': 'a...",Velocity Dance Center,"{'count': 0, 'groups': []}",NaN
73,5d2fa892df98ea8a5fe3591f,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4c23d620f7ced13a07dc216d,"{'address': '6400 36th Ave W.', 'lat': 47.9415...","Boeing, 40-201, Activity Center","{'count': 0, 'groups': []}",NaN
74,5d2fa892df98ea8a5fe35920,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4a7af27af964a520aae91fe3,"{'address': '159 Western Avenue West', 'crossS...",Soul Fitness Club,"{'count': 0, 'groups': []}",{'id': '225922496'}
75,5d2fa892df98ea8a5fe35921,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",45db8910f964a520fb421fe3,"{'address': '35009 Enchanted Pkwy S', 'crossSt...",LA Fitness,"{'count': 0, 'groups': []}",NaN
76,5d2fa892df98ea8a5fe35922,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4bd717657b1876b0af958d86,"{'address': '16521 13th Ave W Ste 104', 'cross...",Hot Yoga of Mill Creek,"{'count': 0, 'groups': []}",{'id': '38784055'}
77,5d2fa892df98ea8a5fe35923,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",45f559fbf964a5200f441fe3,"{'address': '188 106th Ave NE', 'crossStreet':...",24 Hour Fitness,"{'count': 0, 'groups': []}",NaN
78,5d2fa892df98ea8a5fe35924,"[{'id': '4bf58dd8d48988d176941735', 'name': 'G...",4c676e239cb82d7febe693d2,"{'address': '18740 International Blvd', 'cross...",DoubleTree by Hilton Fitness Center,"{'count': 0, 'groups': []}",NaN
79,5d2fa892df98ea8a5fe35925,"[{'id': '4bf58dd8d48988d176941735', 'name': 'G...",49e8f0bef964a520b3651fe3,"{'address': '2820 Rucker Ave', 'lat': 47.97988...",Vertical World Everett,"{'count': 0, 'groups': []}",NaN
80,5d2fa892df98ea8a5fe35926,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b1af72ef964a52091f523e3,"{'address': '748 N 34th St', 'lat': 47.6490497...",Bikram Yoga Seattle,"{'count': 0, 'groups': []}",NaN
81,5d2fa892df98ea8a5fe35927,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",49f0a1e8f964a5203e691fe3,"{'address': '700 5th Ave', 'crossStreet': 'In ...",Seattle Executive Fitness,"{'count': 0, 'groups': []}",NaN
82,5d2fa892df98ea8a5fe35928,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4a7fbf2ef964a5207bf41fe3,"{'address': '1416 NW Ballard Way', 'crossStree...",LA Fitness,"{'count': 0, 'groups': []}",NaN
83,5d2fa892df98ea8a5fe35929,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",5461382c498e552990076245,"{'address': '608 19th Ave E', 'crossStreet': '...",Ritual House,"{'count': 0, 'groups': []}",NaN
84,5d2fa892df98ea8a5fe3592a,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4ac194bff964a520839720e3,"{'address': '1710 S Jackson St Ste 201', 'cros...",The Samarya Center,"{'count': 0, 'groups': []}",NaN
85,5d2fa892df98ea8a5fe3592b,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b8daeb3f964a520510833e3,"{'address': '514 12th Ave Ste B', 'lat': 47.60...",The Yoga Den,"{'count': 0, 'groups': []}",NaN
86,5d2fa892df98ea8a5fe3592c,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4b399eb7f964a5202d5e25e3,"{'address': '5915 6th Ave', 'lat': 47.25620450...",LA Fitness,"{'count': 0, 'groups': []}",NaN
87,5d2fa892df98ea8a5fe3592d,"[{'id': '4bf58dd8d48988d175941735', 'name': 'G...",4bf1cd6278cec92808d8ba86,"{'address': '2nd Division Dr.', 'lat': 47.0823...",Soldier's Field House,"{'count': 0, 'groups': []}",NaN
88,5d2fa892df98ea8a5fe3592e,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b084a08f964a5203e0823e3,"{'address': '317 NW Gilman Blvd Ste 1', 'lat':...",Village Green Yoga & Eco-Boutique,"{'count': 0, 'groups': []}",NaN
89,5d2fa892df98ea8a5fe3592f,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b7b7aa5f964a52001652fe3,"{'address': '525 1st Ave W', 'lat': 47.6239901...",Home Yoga,"{'count': 0, 'groups': []}",NaN
90,5d2fa892df98ea8a5fe35930,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",54f205da498e8baffb1f9079,"{'address': '7700 Aurora Ave N', 'lat': 47.684...",Seattle Holistic Center,"{'count': 0, 'groups': []}",NaN
91,5d2fa892df98ea8a5fe35931,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4c194f9d98f4a593bfe5fff5,"{'address': '4212 University Way NE Ste 202', ...",UniverseCity Yoga,"{'count': 0, 'groups': []}",NaN
92,5d2fa892df98ea8a5fe35932,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b5df3a2f964a520ac7529e3,"{'address': '1621 N 45th St', 'lat': 47.661359...",Sutra Yoga,"{'count': 0, 'groups': []}",NaN
93,5d2fa892df98ea8a5fe35933,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4b02f2b0f964a5204c4b22e3,"{'address': '2113 NE 65th St', 'crossStreet': ...",Community Fitness,"{'count': 0, 'groups': []}",NaN
94,5d2fa892df98ea8a5fe35934,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4ce1c9ba78ddf04d4d66ad98,"{'address': '600 1st Ave Ste 530', 'lat': 47.6...",Aum Yoga Therapy,"{'count': 0, 'groups': []}",NaN
95,5d2fa892df98ea8a5fe35935,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",570b09c4cd1027f1f1369448,"{'address': '1017 E Union St', 'lat': 47.61275...",Métier Yoga,"{'count': 0, 'groups': []}",NaN
96,5d2fa892df98ea8a5fe35936,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4c7585be2db5236a5642bd79,"{'address': '1823 Terry Ave', 'lat': 47.616013...",Aspira Yoga Studio,"{'count': 0, 'groups': []}",NaN
97,5d2fa892df98ea8a5fe35937,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",53fbe690498ed00f02d49cf0,"{'address': '2217 3rd Ave #103', 'crossStreet'...",Levitas Studio,"{'count': 0, 'groups': []}",{'id': '136524872'}
98,5d2fa892df98ea8a5fe35938,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",4a4ef33df964a52035af1fe3,"{'address': '9250 14th Ave NW Rm 2', 'crossStr...",Taj Yoga,"{'count': 0, 'groups': []}",NaN
99,5d2fa892df98ea8a5fe35939,"[{'id': '4bf58dd8d48988d102941735', 'name': 'Y...",5673604a498e9b49cd5ee778,"{'address': '2720 4th Ave Apt 115', 'crossStre...",Breathe Hot Yoga,"{'count': 0, 'groups': []}",NaN

In [4]:
import pandas as pd
df = pd.DataFrame(venues).head().T

In [5]:
df

,0,1,2,3,4
_id,5cc215649282a4c413949195,5cc215649282a4c413949196,5cc215649282a4c413949197,5cc215649282a4c413949198,5cc215649282a4c413949199
beenHere,"{'count': 0, 'lastCheckinExpiredAt': 0, 'marke...","{'count': 0, 'lastCheckinExpiredAt': 0, 'marke...","{'count': 0, 'lastCheckinExpiredAt': 0, 'marke...","{'count': 0, 'lastCheckinExpiredAt': 0, 'marke...","{'count': 0, 'lastCheckinExpiredAt': 0, 'marke..."
categories,"[{'id': '4bf58dd8d48988d176941735', 'name': 'G...","[{'id': '4bf58dd8d48988d176941735', 'name': 'G...","[{'id': '4bf58dd8d48988d176941735', 'name': 'G...","[{'id': '5744ccdfe4b0c0459246b4b2', 'name': 'P...","[{'id': '5744ccdfe4b0c0459246b4b2', 'name': 'P..."
contact,{},{},{},{},{}
hereNow,"{'count': 0, 'summary': 'Nobody here', 'groups...","{'count': 0, 'summary': 'Nobody here', 'groups...","{'count': 1, 'summary': 'One other person is h...","{'count': 0, 'summary': 'Nobody here', 'groups...","{'count': 0, 'summary': 'Nobody here', 'groups..."
id,4597de79f964a5207b401fe3,4a427125f964a520dea51fe3,4a8c22ecf964a520090d20e3,4e31dc941f6e313d8b66fa25,4b6aff32f964a52076eb2be3
location,"{'address': '1325 6th Ave', 'crossStreet': 'at...","{'address': '1813 7th Ave', 'lat': 47.61400529...","{'address': '2020 Western Ave', 'lat': 47.6106...","{'address': '314 1st Ave S', 'lat': 47.5995221...","{'address': '500 E Pike St', 'lat': 47.6134092..."
name,Washington Athletic Club,ZUM fitness,Seattle Athletic Club,Kinesia Pilates Studio,Element Pilates
photos,"{'count': 0, 'groups': []}","{'count': 0, 'groups': []}","{'count': 0, 'groups': []}","{'count': 0, 'groups': []}","{'count': 0, 'groups': []}"
stats,"{'tipCount': 0, 'usersCount': 0, 'checkinsCoun...","{'tipCount': 0, 'usersCount': 0, 'checkinsCoun...","{'tipCount': 0, 'usersCount': 0, 'checkinsCoun...","{'tipCount': 0, 'usersCount': 0, 'checkinsCoun...","{'tipCount': 0, 'usersCount': 0, 'checkinsCoun..."
venuePage,NaN,{'id': '63557214'},NaN,{'id': '48823099'},NaN
verified,False,True,True,True,False

NameError: name 'df' is not defined